version: "3.3"

services:
  backend:
    build: backend
    ports:
      - "8000:8000"
    volumes:
      - static:/app/static

  frontend:
    build: frontend
    volumes:
      - build:/app/build

  nginx:
    build: nginx
    ports:
      - "80:80"
    volumes:
      - build:/var/www/frontend
      - static:/var/www/static
    depends_on:
      - backend
      - frontend

volumes:
  static:
  build:
